# This is a basic workflow to help you get started with Actions

name: Test demos

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - main
    - dev
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: quay.io/fenicsproject/stable:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install FESTIM
        run : pip install festim
      
      - name: Install dependencies
        run : pip install meshio[all]

      # Runs a single command using the runners shell
      - name: Run Task 1
        run: |
          jupyter-nbconvert --to python tasks/task1.ipynb
          python3 -m tasks.task1
      - name: Run Task 2
        run: |
          jupyter-nbconvert --to python tasks/task2.ipynb
          python3 -m tasks.task2
      - name: Run Task 3
        run: |
          jupyter-nbconvert --to python tasks/task3.ipynb
          python3 -m tasks.task3
      - name: Run Task 4
        run: |
          jupyter-nbconvert --to python tasks/task4.ipynb
          python3 -m tasks.task4
      - name: Run Task 5
        run: |
          jupyter-nbconvert --to python tasks/task5.ipynb
          python3 -m tasks.task5
      - name: Run Task 6
        run: |
          jupyter-nbconvert --to python tasks/task6.ipynb
          python3 -m tasks.task6
      - name: Run Task 7
        run: |
          jupyter-nbconvert --to python tasks/task7.ipynb
          python3 -m tasks.task7